version: '2'

services:
  ###
  ### Nginx - Web server and Proxy
  ###
  nginx:
      restart: always
      image: nginx
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - "/etc/nginx/conf.d"
        - "/etc/nginx/vhost.d"
        - "/usr/share/nginx/html"
        - "/opt/appdata/proxy/certs:/etc/nginx/certs:ro"

  ###
  ### Nginx - Creates the web server config files for the containers calling it.
  ###
  nginx-gen:
      restart: always
      image: jwilder/docker-gen
      container_name: nginx-gen
      volumes:
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
        - "/opt/appdata/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
      volumes_from:
        - nginx
      entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  ###
  ### Letsencrypt Nginx Proxy Companion - This is the majic sauce!
  ###
  letsencrypt-nginx-proxy-companion:
      restart: always
      image: jrcs/letsencrypt-nginx-proxy-companion
      container_name: letsencrypt-nginx-proxy-companion
      volumes_from:
        - nginx
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
        - "/opt/appdata/proxy/certs:/etc/nginx/certs:rw"
      environment:
        - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  ghost:
    image: ghost:1-alpine
    container_name: ghost
    restart: always
    ports: 
      - 8085:2368
    volumes:
      - /opt/appdata/ghost:/var/lib/ghost/content
    environment:
#      - VIRTUAL_HOST=blog.SOMEPLACE.COM
#      - VIRTUAL_NETWORK=nginx-proxy
#      - VIRTUAL_PORT=2368
#      - LETSENCRYPT_HOST=blog.SOMEPLACE.COM
#      - LETSENCRYPT_EMAIL=something@someplace.com

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
      - /opt/appdata/sabnzbd:/config
      - /mnt/BigPurple/downloads:/downloads
      - /mnt/BigPurple/downloads/incomplete-downloads:/downloads/incomplete-downloads
    ports:
      - 8080:8080
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
#      - VIRTUAL_HOST=sabnzbd.SOMEPLACE.COM
#      - VIRTUAL_NETWORK=nginx-proxy
#      - VIRTUAL_PORT=8080
#      - LETSENCRYPT_HOST=sabnzbd.SOMEPLACE.COM
#      - LETSENCRYPT_EMAIL=something@someplace.com

  hydra:
    image: linuxserver/hydra
    container_name: hydra
    volumes:
      - /opt/appdata/hydra:/config
      - /mnt/BigPurple/downloads:/downloads
    ports:
      - 5075:5075
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
#     - VIRTUAL_HOST=hydra.SOMEPLACE.COM
#     - VIRTUAL_NETWORK=nginx-proxy
#     - VIRTUAL_PORT=8080
#     - LETSENCRYPT_HOST=hydra.SOMEPLACE.COM
#     - LETSENCRYPT_EMAIL=something@someplace.com

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - sabnzbd
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt/BigPurple/tv:/tv
      - /mnt/BigPurple/downloads:/downloads
    ports:
      - 8989:8989
    links:
      - sabnzbd
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
#      - VIRTUAL_HOST=sonarr.SOMEPLACE.COM
#      - VIRTUAL_NETWORK=nginx-proxy
#      - VIRTUAL_PORT=8989
#      - LETSENCRYPT_HOST=sonarr.SOMEPLACE.COM
#      - LETSENCRYPT_EMAIL=something@someplace.com

  mylar:
    image: linuxserver/mylar
    container_name: mylar
    depends_on:
      - sabnzbd
    volumes:
      - /opt/appdata/mylar:/config
      - /mnt/BigPurple/downloads/comics:/downloads
      - /mnt/BigPurple/comics:/comics
    ports:
      - 8090:8090
    links:
      - sabnzbd
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
#      - VIRTUAL_HOST=sonarr.SOMEPLACE.COM
#      - VIRTUAL_NETWORK=nginx-proxy
#      - VIRTUAL_PORT=8989
#      - LETSENCRYPT_HOST=sonarr.SOMEPLACE.COM
#      - LETSENCRYPT_EMAIL=something@someplace.com

  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/BigPurple/tv:/data/tvshows
      - /mnt/BigPurple/movies:/data/movies
      - /mnt/BigPurple/transcode:/data/transcode
    network_mode: host
    restart: always
      ###
      ### Plex HW transcoding - Install NVIDIA drivers https://www.reddit.com/r/PleX/comments/749hnc/hardware_transcoding_with_plex_docker/
      ###
#    devices:
#      - /dev/dri:/dev/dri
    environment:
      - VERSION=latest
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
  
  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    depends_on:
      - plex
    volumes:
      - /opt/appdata/plexpy:/config
      - /opt/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 8181:8181
    links:
      - plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
#      - VIRTUAL_HOST=plexpy.SOMEPLACE.COM
#      - VIRTUAL_NETWORK=nginx-proxy
#      - VIRTUAL_PORT=8181
#      - LETSENCRYPT_HOST=plexpy.SOMEPLACE.COM
#      - LETSENCRYPT_EMAIL=something@someplace.com
  
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    depends_on:
      - plex
    volumes:
      - /opt/appdata/ombi:/config
    ports:
      - 3579:3579
    links:
      - plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
#      - VIRTUAL_HOST=add.SOMEPLACE.COM
#      - VIRTUAL_NETWORK=nginx-proxy
#      - VIRTUAL_PORT=3579
#      - LETSENCRYPT_HOST=add.SOMEPLACE.COM
#      - LETSENCRYPT_EMAIL=something@someplace.com

  influxdb:
    image: tutum/influxdb
    container_name: influxdb
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - /opt/appdata/influxdb:/data
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on: 
      - influxdb
    links:
      - influxdb
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /opt/appdata/grafana:/var/lib/grafana
    restart: always
    environment:
 #     - VIRTUAL_HOST=grafana.SOMEPLACE.COM
 #     - VIRTUAL_NETWORK=nginx-proxy
 #     - VIRTUAL_PORT=3000
 #     - LETSENCRYPT_HOST=grafana.SOMEPLACE.COM
 #     - LETSENCRYPT_EMAIL=something@someplace.com

  muximux:
    image: linuxserver/muximux
    container_name: muximux
    volumes:
      - /opt/appdata/muximux:/config
    ports:
      - 7777:80
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    #  - VIRTUAL_HOST=media.SOMEPLACE.COM
    #  - VIRTUAL_NETWORK=nginx-proxy
    #  - VIRTUAL_PORT=80
    #  - LETSENCRYPT_HOST=media.SOMEPLACE.COM
    #  - LETSENCRYPT_EMAIL=something@someplace.com

  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /opt/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart:
      always